qcsstudio/linkedin

src/app/api/auth/login/route.js, src/app/api/auth/register/route.js, src/models/client.schema.js, src/models/plan.schema.js, src/models/role.schema.js, src/models/user.schema.js
client,plan,role,user schema created and register updated
=> client,plan,role,user schema created and register updated

src/app/calender/layout.js, src/app/globals.css, src/containers/CalenderContainer/page.js
=> calender with layout

src/app/dashboard/create-post/page.js, src/app/dashboard/settings/feedback/page.js, src/app/globals.css, src/components/AccountComponents/AccountComponent.jsx, src/components/AccountComponents/AddCard.jsx, src/components/AccountComponents/Card.jsx, src/components/AccountComponents/OrganizationCard.jsx, src/components/common/Button.jsx, src/components/common/SideBar.jsx
=> modify-setting

src/components/Navbar.jsx, src/components/ProfileComponent/Avatar.jsx, src/components/ProfileComponent/Personalinformation.jsx, src/components/common/SideBar.jsx
=> modify-sidebar

package-lock.json, src/Context/post.context.js, src/app/api/linkedin/nestedcomment/route.js, src/components/CreatePost/CreatePost.jsx, src/components/EngagementComponents/Posts.jsx
=> nested comments

src/Context/user.context.js, src/app/welcome/page.js, src/components/common/SideBar.jsx, src/containers/WelcomeContainer/WelcomeContainer.jsx
omkar/ logout and welcome added
=> omkar/ logout and welcome added

src/containers/WelcomeContainer/WelcomeContainer.jsx
=> omkar/ welcome bugs

src/Context/post.context.js, src/components/CreatePost/CreatePost.jsx
omkar/ solved generate caption bugs
=> omkar/ solved generate caption bugs

src/Context/post.context.js, src/Context/user.context.js, src/app/api/linkedin/comment/route.js, src/app/api/linkedin/nestedcomment/route.js, src/components/AccountComponents/AccountComponent.jsx, src/components/EngagementComponents/Posts.jsx, src/containers/EngagementContainer/EngagementContainer.jsx, src/containers/WelcomeContainer/WelcomeContainer.jsx
omkar/ comment and nested comment completed
=> omkar/ comment and nested comment completed

src/Context/post.context.js, src/components/EngagementComponents/Posts.jsx
=> omkar/ comment bug solve

src/Context/post.context.js, src/app/api/schedulepost/route.js, src/app/globals.css, src/containers/CalenderContainer/page.js
omkar/ schedule post in month calendar
=> omkar/ schedule post in month calendar

data.txt, package-lock.json, src/Context/user.context.js, src/app/api/auth/user/route.js, src/app/dashboard/layout.js, src/app/globals.css, src/components/Account&Subscription/UserInformation.jsx, src/components/RegisterComponents/RegisterForm.jsx, src/containers/AccountContainer/Account.jsx, src/containers/CalenderContainer/page.js, src/models/user.schema.js
omkar/ week & day schedule show and phone added in register
=> omkar/ week & day schedule show and phone added in register

src/Context/ui.context.js, src/Context/user.context.js, src/app/api/otp/route.js, src/app/api/otp/verify/route.js, src/app/api/password/verify/route.js, src/app/api/user/route.js, src/app/dashboard/layout.js, src/components/ProfileComponent/Personalinformation.jsx, src/components/common/EmailChangePopUp.jsx, src/components/common/PasswordChangePopUp.jsx, src/containers/ProfileContainer/Profile.jsx
omkar/ email,phone,name change via password and otp
=> omkar/ email,phone,name change via password and otp

src/Context/user.context.js
=> omkar/ branch clear commit

next.config.mjs, package-lock.json, package.json, src/Context/ui.context.js, src/app/api/s3-upload-url/route.js, src/app/api/user/route.js, src/app/dashboard/settings/createuser/page.js, src/components/AddUsersComponents/CreateUserForm.jsx, src/components/ProfileComponent/Personalinformation.jsx, src/components/common/EmailChangePopUp.jsx, src/containers/AddUsers/AddUsers.jsx, src/models/user.schema.js
=> omkar/ avatar upload

package-lock.json, src/Context/analytics.context.js, src/app/api/linkedin/all-followers/route.js, src/components/AnalyticsComponets/AllViewsChart.jsx, src/components/AnalyticsComponets/FollowersChart.jsx, src/components/AnalyticsComponets/FollowersOverviewAnalytics.jsx, src/containers/AnalyticsContainer/AnalyticsContianer.jsx
analytics graphs followers and views
=> analytics graphs followers and views

src/Context/user.context.js, src/components/Account&Subscription/TeamMember.jsx, src/components/AccountComponents/AccountComponent.jsx, src/components/AccountComponents/Card.jsx, src/components/AddUsersComponents/CreateUserForm.jsx, src/components/Navbar.jsx, src/components/common/Navbar.jsx, src/components/common/SideBar.jsx, src/containers/AccountContainer/Account.jsx, src/containers/WelcomeContainer/WelcomeContainer.jsx, src/data/sideBar.data.js
omkar/ role based access sidebar filter
=> omkar/ role based access sidebar filter

src/Context/user.context.js, src/app/api/subscription/route.js, src/app/api/subscription/webhook/route.js, src/app/subscription/page.js, src/app/testx/page.js, src/components/HomeComponent/Plans/Plans.jsx, src/containers/SubscriptionComponents/Subscription.jsx, src/containers/SubscriptionContainer/SubscriptionContainer.jsx, src/data/plans.data.js, src/models/user.schema.js
=> omkar/ razor pay integration

src/Context/user.context.js, src/app/api/subscription/route.js
=> omkar/ razor pay bug solve.

src/components/HomeComponent/Footer/Footer.jsx, src/components/HomeComponent/Plans/HomePlan.jsx, src/components/HomeComponent/Plans/Plans.jsx, src/components/HomeComponent/SuccessStories/SuccessStories.jsx, src/data/plans.data.js
This pull request introduces updates to the pricing plans, modifies the footer links, adjusts the duration display logic for pricing plans, and updates a testimonial in the success stories section. Below is a summary of the key changes:
* Added unique `id` fields to each pricing plan object in both `HomePlan.jsx` and `plans.data.js` for better identification and conditional rendering. (`[[1]](diffhunk://#diff-613b8b4d6ccbb8a62c6886d7d3015b15a47c39a20b4ef32e0e7ca2944f9b0245R18)`, `[[2]](diffhunk://#diff-613b8b4d6ccbb8a62c6886d7d3015b15a47c39a20b4ef32e0e7ca2944f9b0245R32)`, `[[3]](diffhunk://#diff-613b8b4d6ccbb8a62c6886d7d3015b15a47c39a20b4ef32e0e7ca2944f9b0245R48)`, `[[4]](diffhunk://#diff-b84de4443cb206ceeccfe72c8fa7b8baa30edcf5b4c998700353f61ace11ce43R3)`, …
=> Add IDs to pricing plans and update footer links for consistency
